//! Human-initiated handoff actions outside a workflow: selecting a variant
//! and opening a draft PR for a finished run.
//!
//! A human running `run pr` is the approval: the policy decision is still
//! evaluated and recorded, a DENY still wins, and the audit records the
//! invoking user as the approving actor.

use anyhow::{bail, Context, Result};

use super::EngineCtx;
use crate::audit::{Actor, EventDraft};
use crate::model::*;
use crate::policies::{Action, Decision, Subject};

pub fn select_variant(ctx: &EngineCtx, task_id: &str, run_ref: &str, user: Option<String>) -> Result<Run> {
    let task = ctx.store.load_task(task_id)?;
    let run = ctx.store.resolve_run(run_ref)?;
    if run.task_id != task.task_id {
        bail!("run {} belongs to task {}, not {}", run.display_name(), run.task_id, task.task_id);
    }
    if run.status != RunStatus::Succeeded {
        bail!("only a succeeded run can be selected (run {} is {})", run.display_name(), run.status.as_str());
    }
    for id in &task.run_ids {
        let mut r = ctx.store.load_run(id)?;
        let sel = r.run_id == run.run_id;
        if r.selected != sel {
            r.selected = sel;
            ctx.store.save_run(&r)?;
        }
    }
    ctx.store.update_task(task_id, |t| {
        t.selected_run = Some(run.run_id.clone());
        Ok(())
    })?;
    ctx.audit(
        EventDraft::new("variant_selected", Actor::human(user))
            .run(&run.run_id, &run.task_id)
            .data(serde_json::json!({"variant": run.variant_label(), "branch": run.git.branch})),
    );
    ctx.store.load_run(&run.run_id)
}

pub fn create_pr_for_run(ctx: &EngineCtx, run_ref: &str, draft: bool, user: Option<String>) -> Result<String> {
    let mut run = ctx.store.resolve_run(run_ref)?;
    if let Some(u) = &run.pr_url {
        return Ok(u.clone());
    }
    if run.status != RunStatus::Succeeded {
        bail!("run {} is {}; only succeeded runs can be handed off", run.display_name(), run.status.as_str());
    }
    let task = ctx.store.load_task(&run.task_id)?;
    let cfg = ctx.load_config(Some(&run.repo_root))?;
    let policy = ctx.policy_for(&cfg)?;
    let wt = run.git.worktree_path.clone().context("run has no worktree")?;
    let branch = run.git.branch.clone().context("run has no branch")?;
    let audit = |ev: &str, actor: Actor, data: serde_json::Value| ctx.audit(EventDraft::new(ev, actor).run(&run.run_id, &run.task_id).data(data));
    for (action, what) in [(Action::GitPush, "push"), (Action::GithubPr, "pull request")] {
        let d = policy.evaluate(&Subject { action: Some(action), branch: Some(branch.clone()), ..Default::default() });
        audit("policy_evaluated", Actor::policy(), serde_json::json!({"subject": d.subject, "decision": d.decision.as_str(), "reason": d.reason}));
        match d.decision {
            Decision::Deny => bail!("policy denies the {what}: {}", d.reason),
            Decision::RequireApproval => audit("approval_granted", Actor::human(user.clone()), serde_json::json!({"via": "explicit CLI handoff", "action": what})),
            Decision::Allow => {}
        }
    }
    if !ctx.gh.available() {
        bail!("GitHub CLI `gh` is not installed");
    }
    if let Some(pr) = ctx.gh.pr_for_branch(&wt, &branch)? {
        run.pr_url = Some(pr.url.clone());
        ctx.store.save_run(&run)?;
        return Ok(pr.url);
    }
    if crate::git::is_dirty(&wt)? {
        bail!("worktree {} has uncommitted changes; commit or discard them first", wt.display());
    }
    crate::git::push_branch(&wt, &cfg.config.git.remote, &branch)?;
    audit("git_pushed", Actor::human(user.clone()), serde_json::json!({"branch": branch}));
    let base = cfg.config.github.base.clone().unwrap_or_else(|| if run.git.base_ref == "HEAD" { "main".into() } else { run.git.base_ref.clone() });
    let body = format!(
        "{}\n\n---\n\nVariant {} of task #{} selected by a human. Generated by herdr-orchestrator run `{}`.\nAudit: `herdr-orchestrator audit verify {}`\n",
        task.description.trim(),
        if run.variant_label().is_empty() { "-".into() } else { run.variant_label() },
        task.task_id,
        run.run_id,
        run.run_id
    );
    let url = ctx.gh.pr_create(&wt, &base, &branch, &task.title, &crate::audit::redact::redact_str(&body), draft)?;
    run.pr_url = Some(url.clone());
    run.artifacts.push(Artifact { kind: "pull_request".into(), name: "PR".into(), path: None, url: Some(url.clone()), step_id: None, created_at: now() });
    ctx.store.save_run(&run)?;
    audit("pr_created", Actor::human(user), serde_json::json!({"url": url, "draft": draft}));
    Ok(url)
}
